### ISSUE TITLE
Voltage 5v dropped when i put inductor and Error

### ISSUE THREAD

**Issue by TeguhTeknisi** [5VLogic/l_meter#2]
Hi 5Volt,

I try to build it, using schematic from your youtube video.
But i replace BD137 to BD139.
R 500 Ohm to 510 Ohm.
Diode 1N4007 to 1N4002.

Using mkp 100nF 63v,
2200uF 16V Elco,
And multilayer ceramic 470nF 50v.

With Arduino Pro Mini 328BP 5Volt.

Power using AMS-1117 5.0V with 9Volt.

When i put the inductor, its 470 Ohm from damaged LM2596 Buck Converter module.

The voltage 5V will drop to 2.8V and Arduino pro mini will shut down.

Is try to re check the board, looks like, there is nothing wrong.

Here the picture
1.Before i put the inductor
<img src="https://github.com/5VLogic/l_meter/assets/32675055/1f12e603-1677-45b0-9757-2a81d0a98cbf" width="169" height="300">
2. When i put the inductor
<img src="https://github.com/5VLogic/l_meter/assets/32675055/3232f318-9987-47fa-9fae-9c2cfe2c8445" width="169" height="300">
3. voltage drop
<img src="https://github.com/5VLogic/l_meter/assets/32675055/720bd1c9-3d62-4b13-abb8-73b4535a42de" width="169" height="300">

The pictures of my board ( click to make it bigger )
<img src="https://github.com/5VLogic/l_meter/assets/32675055/b2427c20-eb24-497e-8a9b-920a1ee8eab9" width="300" height="169">
<img src="https://github.com/5VLogic/l_meter/assets/32675055/291ff735-2fa6-456d-9544-fdf1a32e7cc9" width="300" height="169">
<img src="https://github.com/5VLogic/l_meter/assets/32675055/ace6f948-6f77-4983-aa01-e9b91f431234" width="169" height="300">

Or there is something wrong with the code?
Here the code:
```
#define F_CPU 16000000
#define ARRAY_LEN 6
#define STR_LEN 16
#define CONST 1010647491 // Approximate result of 4 pi^2 16MHz^2 C / 1'000
#define DELTA_MAX 20

#include <avr/io.h>
#include <avr/interrupt.h>
#include <util/delay.h>
#include <stdio.h>

// LCD OLED 
#include <Adafruit_GFX.h>
#include <Adafruit_SSD1306.h>
#define SCREEN_WIDTH 128 // OLED display width, in pixels
#define SCREEN_HEIGHT 64 // OLED display height, in pixels
#define OLED_RESET -1  // Reset pin # (or -1 if sharing Arduino reset pin)
Adafruit_SSD1306 display(SCREEN_WIDTH, SCREEN_HEIGHT, &Wire, OLED_RESET);


uint8_t i, flag, power, divisor;

uint16_t val[ARRAY_LEN];
uint16_t dmin, dmax;

uint32_t davg, davgsquared, L, Ldecimal, denominator;

char string[STR_LEN];


/* Interrupt service routine called by TC1 for every input capture signal.
 * Resets counter on first time being called.
 * Fills 'val' array with every subsequent call with absoulute time.
 * Updates flag every call to know how many times it has been called.
 */
ISR(TIMER1_CAPT_vect)
{
  if(flag == 0)
    TCNT1 = 0;

  else if(flag <= ARRAY_LEN)
    val[flag - 1] = ICR1;

  flag++;
}



void setup() {
  Serial.begin(9600);
  Serial.println(F(""));
  Serial.println(F("Start Booting..."));
 
  // I2C
  Wire.begin();
  // OLED
  display.begin(SSD1306_SWITCHCAPVCC, 0x3C);  // initialize with the I2C addr 0x3C (for the 64x48)
  // OLED init done

  // Clear the buffer.
  display.clearDisplay();

  display.setCursor(0, 0);
  display.setTextSize(1);
  display.setTextColor(WHITE);
  display.println("Induktor Meter");
  display.println("Oleh Teguh Sakura");
  display.println("=====================");
  display.setCursor(0, 15);
  display.print("Ver 1.0");
  display.display();

    
  // Pins A0 - A5 outputs
  DDRC = 0b00111111;

  // Pin D1 as output (transistor base)
  DDRD |= (1 << PD1);

  // Enable global interrupt
  SREG |= (1 << 7);

  // Setup of AC
  ACSR &= ~(1 << ACD);// Enable AC
  ACSR &= ~(1 << ACBG);// Disable bandgap reference
  ADCSRB |= (1 << ACME);// Enable Mux
  ADCSRA &= ~(1 << ADEN);// Disable ADC
  ADMUX |= 0b00000111;// Select ADC7 pin as inverting input of AC


  // Setup of time TC1
  ACSR |= (1 << ACIC);// Select AC as TC1 input capture trigger
  TCCR1B |= 0b00000001;// Use prescaler = 1
  PRR &= ~(1 << PRTIM1);// Disable Power reduction to TC1
  TCCR1B |= (1 << ICNC1);// Enable noise cancelling (optional)
  TIMSK1 |= (1 << ICIE1);// Input capture interrupt enable for TC1

  Serial.println(F("Booting Done...."));
}

void loop()
{
    _delay_ms(500);

    flag = 0;

    // Set Pin D1 to HIGH
    PORTD |= (1 << PD1);

    // Delay for approx 250 ns
    asm("nop");
    asm("nop");
    asm("nop");


    TCNT1 = 0;
    // Pin D1 to LOW
    PORTD &= ~(1 << PD1);

    _delay_ms(100);

    // 'Divisor' is the number of valid periods measured
    divisor = ARRAY_LEN - 1;

    dmax = 0;
    dmin = 0xffff;

    // loop through all values (periods)
    for(i = ARRAY_LEN - 1; i > 0; i--)
    {
      // if a value is null, kepp track with "divisor" and skip loop
      if(val[i] == 0){
        divisor = i - 1;
        continue;
      }
      // Find maximum period
      if(val[i] - val[i - 1] > dmax)
        dmax = val[i] - val[i - 1];

      // Find minumum period
      if(val[i] - val[i - 1] < dmin)
        dmin = val[i] - val[i - 1];
    }

    // Calculate average period of oscillation
    davg = (uint32_t)(val[divisor] - val[0]) / ((uint32_t)divisor);
    davgsquared = davg * davg;
    denominator = CONST;

    // Find power of denominator such that L is n*100 e-m for decimal formatting
    L = davgsquared / denominator;
    for(power = 0; L < 100; power++)
    {
      denominator /= 10;
      L = davgsquared / denominator;
    }
    // Because of rounding error, L can go from 99 -> 1000, must catch!
    if(L >= 1000){
      L /=10;
      power--;
    }

    sprintf(string, "%d", (uint16_t)L);

    // Insert '.' at correct position inside the string representing the decimal
    if(power % 3)
    {
      for(i = STR_LEN - 1; i >= 4 - (power % 3); i--)
        string[i] = string[i - 1];

      string[i] = '.';
    }

    // Check validity of the measurements
    if(dmin <= davg &&\
      davg <= dmax &&\
      dmin > 0 &&\
      ((uint16_t)davg) / (dmax - dmin) >= DELTA_MAX)
    {
      Serial.println(string);
      display.clearDisplay();
      display.setCursor(0, 0);
      display.setTextSize(1);
      display.setTextColor(WHITE);
      display.println("Induktor Meter");
      display.println("Oleh Teguh Sakura");
      display.println("=====================");
      display.setTextSize(2);
      display.setCursor(0, 35);
      display.print(string);
        
      if(power >= 9) {
        Serial.print(F("nH"));
        display.setCursor(0, 35);
        display.println(" nH");
        display.display();
      }
      else if(power >= 6) {
        Serial.print(F("uH"));
        display.setCursor(0, 35);
        display.println(" uH");
        display.display();
      }  
      else if(power >= 3)
        Serial.print(F("mH"));
        display.setCursor(0, 35);
        display.println(" mH");
        display.display();
    
    }

    else if(dmin == 0xffff) {
      Serial.println(F("Open"));
      display.clearDisplay();
      display.setCursor(0, 0);
      display.setTextSize(1);
      display.setTextColor(WHITE);
      display.println("Induktor Meter");
      display.println("Oleh Teguh Sakura");
      display.println("=====================");
      display.setTextSize(2);
      display.setCursor(0, 35);
      display.print("Open");
      display.display();
    }
    else {
      Serial.println(F("Error"));
      display.clearDisplay();
      display.setCursor(0, 0);
      display.setTextSize(1);
      display.setTextColor(WHITE);
      display.println("Induktor Meter");
      display.println("Oleh Teguh Sakura");
      display.println("=====================");
      display.setTextSize(2);
      display.setCursor(0, 35);
      display.print("Error");
      display.display();
    }
    for(i = 0; i < ARRAY_LEN; i++)
      val[i] = 0;

}
```

Best Regrads,
Teguh

**Comment by 5VLogic** [comment]
Hi Teguh,

hardware problem are a little more difficult to solve online (and in person as well in my opinion).

What I can do is give a few suggestions.
1) If you have an oscilloscope, probe all the signals and the power supply to the arduino and try to establish the cause of the voltage drop.
2) If you connected your pre-regulated supply to the Vin pin of the arduino it might be that the onboard regulator is causing a voltage drop.
2a. In particular if you put the main decoupling and supply capacitors on the Vin side of things, this means that the regulator has to provide the high current at the moment of energizing the coil.
I recommend to connect the supply to the 5V pin (bypassing the arduino's regulator) and the decoupling capacitors as close as possible. This should only be done if you're confident of your supply's regulation, otherwise it can damage the arduino if it goes above 5V.
3) If nothing works you can try to set breakpoints in the code by adding a `return;` at different points in the `loop()` function and see what causes the voltage drop. Particularly if it's before or after the coil is energized.
A `return;` in the  `loop()` will simply make it start over again, as the hidden `main()` will call it continuously.

I really hope this helps!

**Comment by TeguhTeknisi** [comment]
> Hi Teguh,
> 
> hardware problem are a little more difficult to solve online (and in person as well in my opinion).
> 
Yes, it's true.

> What I can do is give a few suggestions.
> 
> 1. If you have an oscilloscope, probe all the signals and the power supply to the arduino and try to establish the cause of the voltage drop.

I have Fnirsi DSO 152, 
I thought, it because the signal to turn on and off the BD139 is the problem.
So, i have probe TX prin ( D1 ), some times there is a signal, but some times is no pulse.

is there some video, about how to to tes the TX Pin pulse for BD137?


> 2. If you connected your pre-regulated supply to the Vin pin of the arduino it might be that the onboard regulator is causing a voltage drop.

i dont use onboard regulator, because in the schematic, its look like need more power than the onboard regulator could give the power,
so i use linear regulator  ams 117 5.0 and  the output Ams-1117 5.0 goes directly to 2200uF 16v and the Coil
Do i need to change it, using LM7805 so i can give more current?
But using ams1117 its make the ams1117 versy hot for couple of times

>    2a. In particular if you put the main decoupling and supply capacitors on the Vin side of things, this means that the regulator has to provide the high current at the moment of energizing the coil.
>    I recommend to connect the supply to the 5V pin (bypassing the arduino's regulator) and the decoupling capacitors as close as possible. This should only be done if you're confident of your supply's regulation, otherwise it can damage the arduino if it goes above 5V.

That what i do.

> 3. If nothing works you can try to set breakpoints in the code by adding a `return;` at different points in the `loop()` function and see what causes the voltage drop. Particularly if it's before or after the coil is energized.
>    A `return;` in the  `loop()` will simply make it start over again, as the hidden `main()` will call it continuously.
> 

Thanks for the sugestion.
So the code make the BD137 to turn on for how long? and turn off after how long?
Or its using PWM signal? what's the frequency?


> I really hope this helps!

Thanks for the reply.
Still hope to make this working.

**Comment by 5VLogic** [comment]
Hi Teguh,

> is there some video, about how to to test the TX Pin pulse for BD137?

I'm not sure, I haven't made one though.

> Do i need to change it, using LM7805 so i can give more current?

I'm not familiar with the  ams 117 5.0, you should check the datasheet and figure out what it's maximum current is.
Although if the problem is that there's a short circuit, then that should be fixed, and not the regulator changed.

> So the code make the BD137 to turn on for how long? and turn off after how long?

If the clock frequency is 16MHz (which I believe is default for all common arduinos) then the three `nop` instructions
should be 62.5ns each, including the time to execute the following instruction makes 250ns as written in the code comment `// Delay for approx 250 ns`.

> Or its using PWM signal? what's the frequency?

Just a single pulse.




Good luck on the project!

**Comment by TeguhTeknisi** [comment]
> Hi Teguh,
> 
> > is there some video, about how to to test the TX Pin pulse for BD137?
> 
> I'm not sure, I haven't made one though.
> 
> > Do i need to change it, using LM7805 so i can give more current?
> 
> I'm not familiar with the  ams 117 5.0, you should check the datasheet and figure out what it's maximum current is.
> Although if the problem is that there's a short circuit, then that should be fixed, and not the regulator changed.
> 

Ams 1117 5.0 max current 800mA.
I will try to change the transistor and the base resistor.

> > So the code make the BD137 to turn on for how long? and turn off after how long?
> 
> If the clock frequency is 16MHz (which I believe is default for all common arduinos) then the three `nop` instructions
> should be 62.5ns each, including the time to execute the following instruction makes 250ns as written in the code comment `// Delay for approx 250 ns`.
> 
> > Or its using PWM signal? what's the frequency?
> 
> Just a single pulse.
> 
> 
> 
> 
> Good luck on the project!

Thanks, i still try to learn the code using your video in the capacitance meter.
( https://youtu.be/KNtriMa4RaI?si=yBYrR0xNsxwsxvpA )
This the first time and project using atmega 328p and because i need inductance meter.
What is the smd transistor you use in the pcb board?
Do you have the schematic or gerber file?



Btw, which better for making lc meter.
using atmega 328p or pic 16f628 ?

Looking this https://sites.google.com/site/vk3bhr/home/index2-html

Its looks like more accurate? Or just the same?

Thanks for the reply.

Best regrads,
Teguh.

**Comment by TeguhTeknisi** [comment]
i close it, because i give up, perhaps in the future when i have time, i will try it again.
thanks.

Best regrads,
Teguh
